-- MySQL Script generated by MySQL Workbench
-- Mon Jun 15 11:38:04 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema whoapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema whoapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `whoapp_test`
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_unicode_ci;
USE `whoapp_test`;

-- -----------------------------------------------------
-- Table `whoapp_test`.`user_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`user_status` (
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `whoapp_test`.`roles_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`roles_group` (
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`user` (
  `id`                 INT          NOT NULL AUTO_INCREMENT,
  `username`           VARCHAR(30)  NOT NULL,
  `password`           VARCHAR(100) NOT NULL,
  `date_creation`      MEDIUMTEXT   NOT NULL,
  `network_status`     TINYINT(1)   NOT NULL,
  `last_date_activity` MEDIUMTEXT   NOT NULL,
  `friends_request`    TINYINT(1)   NOT NULL,
  `user_status_id`     INT          NOT NULL,
  `roles_group_id`     INT          NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_status1_idx` (`user_status_id` ASC),
  INDEX `fk_users_roles_groups1_idx` (`roles_group_id` ASC),
  CONSTRAINT `fk_users_user_status1`
  FOREIGN KEY (`user_status_id`)
  REFERENCES `whoapp_test`.`user_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles_groups1`
  FOREIGN KEY (`roles_group_id`)
  REFERENCES `whoapp_test`.`roles_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`country` (
  `id`      INT         NOT NULL,
  `name_ru` VARCHAR(45) NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`city` (
  `id`          INT         NOT NULL,
  `name_ru`     VARCHAR(45) NOT NULL,
  `district_ru` VARCHAR(75) NULL,
  `country_id`  INT         NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country1`
  FOREIGN KEY (`country_id`)
  REFERENCES `whoapp_test`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8
  PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `whoapp_test`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`user_details` (
  `id`           INT         NOT NULL AUTO_INCREMENT,
  `first_name`   VARCHAR(45) NULL     DEFAULT NULL,
  `last_name`    VARCHAR(45) NULL     DEFAULT NULL,
  `sex`          TINYINT(1)  NULL,
  `phone_number` VARCHAR(15) NULL     DEFAULT NULL,
  `birthday`     MEDIUMTEXT  NULL     DEFAULT NULL,
  `avatar`       BLOB        NULL     DEFAULT NULL,
  `email`        VARCHAR(45) NOT NULL,
  `city_id`      INT         NULL     DEFAULT NULL,
  `user_id`      INT         NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `phone_number` (`phone_number` ASC),
  INDEX `fk_user_details_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `user_id` (`user_id` ASC),
  INDEX `fk_city_idx` (`city_id` ASC),
  CONSTRAINT `fk_user`
  FOREIGN KEY (`user_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_city`
  FOREIGN KEY (`city_id`)
  REFERENCES `whoapp_test`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`place_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`place_status` (
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`place` (
  `id`              INT         NOT NULL AUTO_INCREMENT,
  `name`            VARCHAR(50) NOT NULL,
  `place_status_id` INT         NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_place_place_status1_idx` (`place_status_id` ASC),
  INDEX `name_index` (`name` ASC),
  CONSTRAINT `fk_place_place_status1`
  FOREIGN KEY (`place_status_id`)
  REFERENCES `whoapp_test`.`place_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`location` (
  `id`        INT    NOT NULL AUTO_INCREMENT,
  `latitude`  DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `place_id`  INT    NULL     DEFAULT NULL,
  `user_id`   INT    NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_place_idx` (`place_id` ASC),
  INDEX `fk_location_users_idx` (`user_id` ASC),
  UNIQUE INDEX `place_id_UNIQUE` (`place_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `fk_location_place`
  FOREIGN KEY (`place_id`)
  REFERENCES `whoapp_test`.`place` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_user`
  FOREIGN KEY (`user_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`place_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`place_details` (
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `description` TEXT(350)    NOT NULL,
  `address`     VARCHAR(100) NOT NULL,
  `site`        VARCHAR(45)  NULL     DEFAULT NULL,
  `phone`       VARCHAR(45)  NULL     DEFAULT NULL,
  `proposition` VARCHAR(255) NULL     DEFAULT NULL,
  `place_id`    INT          NOT NULL,
  `city_id`     INT          NOT NULL,
  PRIMARY KEY (`id`, `place_id`, `city_id`),
  INDEX `fk_place_details_place1_idx` (`place_id` ASC),
  INDEX `fk_place_details_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_place_details_place1`
  FOREIGN KEY (`place_id`)
  REFERENCES `whoapp_test`.`place` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_place_details_city1`
  FOREIGN KEY (`city_id`)
  REFERENCES `whoapp_test`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`activity` (
  `id`             INT         NOT NULL AUTO_INCREMENT,
  `initiator_id`   INT         NOT NULL,
  `participant_id` INT         NULL     DEFAULT NULL,
  `interest_id`    INT         NULL     DEFAULT NULL,
  `interest_name`  VARCHAR(45) NULL     DEFAULT NULL
  COMMENT 'interest name if interest_id isn’t provided',
  `place_id`       INT         NULL     DEFAULT NULL,
  INDEX `fk_initiator_id_idx` (`initiator_id` ASC),
  INDEX `fk_participant_id_idx` (`participant_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_activity_place1_idx` (`place_id` ASC),
  CONSTRAINT `fk_initiator_id`
  FOREIGN KEY (`initiator_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant_id`
  FOREIGN KEY (`participant_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_place1`
  FOREIGN KEY (`place_id`)
  REFERENCES `whoapp_test`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`interest` (
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name_index` (`name` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`user_persistent_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`user_persistent_interest` (
  `users_id`     INT NOT NULL,
  `interests_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `interests_id`),
  INDEX `fk_users_persistent_interest_users1_idx` (`users_id` ASC),
  INDEX `fk_users_persistent_interest_interests1_idx` (`interests_id` ASC),
  CONSTRAINT `fk_users_persistent_interest_users1`
  FOREIGN KEY (`users_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_persistent_interest_interests1`
  FOREIGN KEY (`interests_id`)
  REFERENCES `whoapp_test`.`interest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`user_current_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`user_current_interest` (
  `user_id`       INT        NOT NULL,
  `interest_id`   INT        NOT NULL,
  `activity_time` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`user_id`, `interest_id`),
  INDEX `fk_users_current_interests_users1_idx` (`user_id` ASC),
  INDEX `fk_users_current_interests_interests1_idx` (`interest_id` ASC),
  CONSTRAINT `fk_users_current_interests_users1`
  FOREIGN KEY (`user_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_current_interests_interests1`
  FOREIGN KEY (`interest_id`)
  REFERENCES `whoapp_test`.`interest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`place_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`place_interest` (
  `place_id`     INT NOT NULL,
  `interests_id` INT NOT NULL,
  PRIMARY KEY (`place_id`, `interests_id`),
  INDEX `fk_place_interests_place1_idx` (`place_id` ASC),
  INDEX `fk_place_interests_interests1_idx` (`interests_id` ASC),
  CONSTRAINT `fk_place_interests_place1`
  FOREIGN KEY (`place_id`)
  REFERENCES `whoapp_test`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_place_interests_interests1`
  FOREIGN KEY (`interests_id`)
  REFERENCES `whoapp_test`.`interest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`rating` (
  `user_id`  INT NOT NULL,
  `place_id` INT NOT NULL,
  `value`    INT NOT NULL,
  PRIMARY KEY (`user_id`, `place_id`),
  INDEX `fk_ratings_users1_idx` (`user_id` ASC),
  INDEX `fk_ratings_place1_idx` (`place_id` ASC),
  CONSTRAINT `fk_ratings_users1`
  FOREIGN KEY (`user_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ratings_place1`
  FOREIGN KEY (`place_id`)
  REFERENCES `whoapp_test`.`place` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`friend` (
  `user_id`   INT NOT NULL,
  `friend_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `friend_id`),
  INDEX `fk_firends_users2_idx` (`friend_id` ASC),
  CONSTRAINT `fk_firends_users1`
  FOREIGN KEY (`user_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_firends_users2`
  FOREIGN KEY (`friend_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`friends_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`friends_request` (
  `initiator_user_id` INT NOT NULL,
  `target_user_id`    INT NOT NULL,
  PRIMARY KEY (`initiator_user_id`, `target_user_id`),
  INDEX `fk_friends_requests_users1_idx` (`initiator_user_id` ASC),
  INDEX `fk_friends_requests_users2_idx` (`target_user_id` ASC),
  CONSTRAINT `fk_friends_requests_initiator`
  FOREIGN KEY (`initiator_user_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friends_requests_target`
  FOREIGN KEY (`target_user_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`message` (
  `id`           INT          NOT NULL AUTO_INCREMENT,
  `body`         VARCHAR(255) NOT NULL,
  `recipient_id` INT          NULL     DEFAULT NULL,
  `activity_id`  INT          NULL     DEFAULT NULL,
  `sender_id`    INT          NOT NULL,
  `timestamp`    MEDIUMTEXT   NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_users1_idx` (`sender_id` ASC),
  CONSTRAINT `fk_messages_users1`
  FOREIGN KEY (`sender_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`search_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`search_request` (
  `id`            INT         NOT NULL AUTO_INCREMENT,
  `requestor_id`  INT         NOT NULL,
  `interest_id`   INT         NULL     DEFAULT NULL,
  `interest_name` VARCHAR(45) NULL     DEFAULT NULL,
  `timestamp`     MEDIUMTEXT  NOT NULL,
  `user_id`       INT         NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_requests_user_idx` (`user_id` ASC),
  INDEX `fk_search_request_interest_idx` (`interest_id` ASC),
  CONSTRAINT `fk_request_user`
  FOREIGN KEY (`user_id`)
  REFERENCES `whoapp_test`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_search_requests_interests1`
  FOREIGN KEY (`interest_id`)
  REFERENCES `whoapp_test`.`interest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`role` (
  `id`   INT         NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `whoapp_test`.`role_roles_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whoapp_test`.`role_roles_group` (
  `role_id`        INT NOT NULL,
  `role_groups_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `role_groups_id`),
  INDEX `fk_roles_roles_groups_roles1_idx` (`role_id` ASC),
  INDEX `fk_roles_roles_groups_roles_groups1_idx` (`role_groups_id` ASC),
  CONSTRAINT `fk_roles_roles_groups_roles1`
  FOREIGN KEY (`role_id`)
  REFERENCES `whoapp_test`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_roles_groups_roles_groups1`
  FOREIGN KEY (`role_groups_id`)
  REFERENCES `whoapp_test`.`roles_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB
  COLLATE = utf8_unicode_ci
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
